services:
  wuzmind-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/douglassilsouza/wuzmind-service:latest
    container_name: wuzmind-service
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - .env

    networks:
      - ContasNet

    volumes:
      - /opt/gastoapp/envs/wuzmind-service.env:/app/.env

    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=ContasNet
        - traefik.http.routers.wuzmind.rule=Host(`wuzmind.dsilvamoda.cloud`)
        - traefik.http.routers.wuzmind.entrypoints=websecure
        - traefik.http.routers.wuzmind.tls=true
        - traefik.http.routers.wuzmind.tls.certresolver=letsencryptresolver
        - traefik.http.services.wuzmind.loadbalancer.server.port=3000

networks:
  ContasNet:
    external: true
    name: ContasNet
