export enum MediaClassificationEnum {
  COMPROVANTE = 'COMPROVANTE',
  FATURA = 'FATURA',
  EXTRATO = 'EXTRATO',
  AUDIO_DESPESA = 'AUDIO_DESPESA',
  AUDIO_DUVIDA = 'AUDIO_DUVIDA',
  DOCUMENTO_OUTRO = 'DOCUMENTO_OUTRO',
  IMAGEM_OUTRA = 'IMAGEM_OUTRA',
  DESCONHECIDO = 'DESCONHECIDO',
}
