export enum SuggestedActionEnum {
  CONTINUE_TYPEBOT = 'CONTINUE_TYPEBOT',
  START_TYPEBOT_FLOW = 'START_TYPEBOT_FLOW',
  REDISPLAY_MENU = 'REDISPLAY_MENU',
  RESET_SESSION = 'RESET_SESSION',
  END_SESSION = 'END_SESSION',
  SEND_TO_N8N_OCR = 'SEND_TO_N8N_OCR',
  SEND_TO_N8N_TRANSCRIPTION = 'SEND_TO_N8N_TRANSCRIPTION',
  ANSWER_AND_KEEP_STATE = 'ANSWER_AND_KEEP_STATE',
  STATIC_FALLBACK = 'STATIC_FALLBACK',
  NO_ACTION = 'NO_ACTION',
}
